# Configurations
markdown: kramdown

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            '獨孤求敗'
tagline:          '学而时习之，不亦乐乎'
description:      '一个差时症患者'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'Abdel Raoof Olakara'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/no1guangming'
flickr:
github:         'https://github.com/no1guangming'
gplus:          'https://plus.google.com/u/0/118275603698592104802'
instagram:      
pinterest:
linkedin:       'https://www.linkedin.com/in/no1guangming/'
rss:
stackoverflow:  'https://stackoverflow.com/users/10936561/'
twitter:        'https://twitter.com/no1guangming'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'



# txtpen
txtpenhandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
