# Configurations
markdown: kramdown

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            '獨孤求敗'
tagline:          '学而时习之，不亦乐乎'
description:      '一个差时症患者'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         '王光明'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       'https://www.facebook.com/no1guangming'
flickr:
github:         'https://github.com/no1guangming'
douban:          'https://www.douban.com/people/no1guangming/'
instagram:      
pinterest:
linkedin:       'https://www.linkedin.com/in/no1guangming/'
rss:
stackoverflow:  'https://stackoverflow.com/users/10936561/'
twitter:        'https://twitter.com/no1guangming'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# GitTalk
GitTalk:
  enable: true
  clientID: 'aa1c5f6fa8bde34b2855'
  clientSecret: 'a5ec69201e60958beffaba8ace8fb48151a58c1b'
  repo: 'no1guangming.github.io'
  owner: 'no1guangming'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
